name: Fairchild Consortium
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50553
title: Fairchild Consortium
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#555555'
    - '#a9a9a9'
    - '#353535'
    - '#151515'
  brandStrength: 0.5
  lightness: 0.34351557050831616
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
